all:
	cd 1-array-string && $(MAKE) all
	cd 3-stack-queue && $(MAKE) all

clean:
	cd 1-array-string && $(MAKE) clean
	cd 3-stack-queue && $(MAKE) clean

build:
	cd 1-array-string && $(MAKE) build
	cd 3-stack-queue && $(MAKE) build

test:
	cd 1-array-string && $(MAKE) test
	cd 3-stack-queue && $(MAKE) test
