language: cpp
sudo: false

# List of apt packages available from Travis CI
# can be found at: https://github.com/travis-ci/apt-package-whitelist
addons_shortcuts:
  addons_clang39: &clang39
    apt:
      sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports', 'llvm-toolchain-precise-3.9']
      packages: ['clang++-3.9', 'cmake', 'cmake-data', 'libgtest-dev']
  addons_gcc49: &gcc49
    apt:
      sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
      packages: ['g++-4.9', 'cmake', 'cmake-data', 'libgtest-dev']

matrix:
  include:
    - os: linux
      compiler: "clang-3.9"
      env: CC=clang-3.9 CXX=clang++-3.9 CXX_STD=c++14
      addons: *clang39
    - os: linux
      compiler: "g++-4.9"
      env: CC=gcc-4.9 CXX=g++-4.9 CXX_STD=c++14
      addons: *gcc49

before_install:
  - mkdir gtest-build
  - mkdir build/
  - pushd gtest-build
  - cmake /usr/src/gtest
  - make
  - popd

script:
  - cmake .
  - make -j4
  - make test ARGS="-V"
