language: cpp
sudo: false

# List of apt packages available from Travis CI
# can be found at: https://github.com/travis-ci/apt-package-whitelist
addons_shortcuts:
  addons_clang39: &clang39
    apt:
      sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports', 'llvm-toolchain-precise-3.9']
      packages: ['clang-3.9', 'cmake', 'cmake-data', 'libgtest-dev']
  addons_gcc49: &gcc49
    apt:
      sources: ['ubuntu-toolchain-r-test', 'george-edison55-precise-backports']
      packages: ['g++-4.9', 'cmake', 'cmake-data', 'libgtest-dev']

matrix:
  include:
    - os: linux
      compiler: clang
      env: COMPILER_VERSION=3.9
      addons: *clang39
    - os: linux
      compiler: gcc
      env: COMPILER_VERSION=4.9
      addons: *gcc49

install: 
  - mkdir ~/gtest && cd ~/gtest
  - export LIBRARY_PATH=$(pwd)
  - cp -r /usr/src/gtest/* ./
  - cmake -D CMAKE_INSTALL_PREFIX:PATH=./ ./
  - make
  - cd -

script:
  - ls -alhR ~/gtest
  - export GTEST_LIBRARY="~/gtest/libgtest.a"
  - export GTEST_MAIN_LIBRARY="~/gtest/libgtest_main.a"
  - export CC="${CC}-${COMPILER_VERSION}"
  - export CXX="${CXX}-${COMPILER_VERSION}"
  - export CXX_STD="c++14"
  - cmake .
  - make -j4
  - make test ARGS="-V"
