language: cpp
sudo: required

compiler:
- clang
- g++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - gcc-4.8
    - g++-4.8

os:
- linux

script:
- cmake .
- make -j4
- make test ARGS="-V"
