language: cpp
dist: trusty
sudo: required

addons_shortcuts:
  addons_clang39: &clang39
    apt:
      sources: ['ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.9']
      packages: ['clang-3.9']
  addons_gcc49: &gcc49
    apt:
      sources: ['ubuntu-toolchain-r-test']
      packages: ['g++-4.9', 'gcc-4.9']

matrix:
  include:
    - os: linux
      compiler: "clang-3.9"
      env: CC=clang-3.9 CXX=clang++-3.9 CXX_STD=c++14
      addons: *clang39M
    - os: linux
      compiler: "g++-4.9"
      env: CC=gcc-4.9 CXX=g++-4.9 CXX_STD=c++14
      addons: *gcc49

install:
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest
  - sudo cmake .
  - sudo make
  - sudo mv libgtest* /usr/lib/
  - cd "${TRAVIS_BUILD_DIR}"

script:
  - cmake .
  - make -j4
  - make test ARGS="-V"
