version: 1.0.{build}
os: Visual Studio 2015

environment:
  matrix:
  - CMAKE_BUILD_TYPE: Release
    ARCH: x86

install:
- git clone https://github.com/google/googletest.git
- cd googletest
- "\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" %ARCH%"
- cmake .
- nmake
- cd ..
- git submodule update --init --recursive

build_script:
- "\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" %ARCH%"
- cmake .
- nmake

test_script:
- ctest -VV
