version: 1.0.{build}
os: Visual Studio 2015

environment:
  matrix:
  - ARCH: amd64
  - ARCH: x86

install:
- cmd: echo "Downloading conan..."
- cmd: set PATH=%PATH%;%PYTHON%/Scripts/
- cmd: pip.exe install conan
- cmd: conan user # Create the conan data directory
- cmd: conan --version
- git submodule update --init --recursive

build_script:
- cmd: conan install -o gtest:shared=True
- "\"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat\" %ARCH%"
- cmake -DCMAKE_BUILD_TYPE=Release -G "NMake Makefiles" .
- nmake

test_script:
- ctest -VV
